name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Adjust if you use a different default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v

      - name: Build Docker image
        run: docker build -t logan2507/portfolio:v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.logan2507 }}
          password: ${{ secrets.10qpalzm@ }}

      - name: Push Docker image
        run: |
          docker tag logan2507/portfolio:v2 logan2507/portfolio:v2
          docker push logan2507/portfolio:v2
